
    - name: Create the disk group
      command: >-
               /usr/bin/docker exec {{ first_rac_node }}
               /usr/bin/su -
               {{
                 operating_system.grid_infrastructure.users |
                 selectattr('title', 'equalto', 'owner') |
                 map(attribute='name') |
                 first
               }} -c "ORACLE_SID=+ASM1
               {{
                 oracle_binaries |
                 selectattr('type', 'equalto', 'grid') |
                 selectattr('version', 'equalto', '12.1.0.2') |
                 map(attribute='oracle_home') | first
               }}/bin/asmcmd mkdg '
               <dg name=\"{{ this_disk_group }}\" redundancy=\"external\">
               {% for disk in asm_disk_groups |
                  selectattr('group', 'equalto', this_disk_group) |
                  list | map(attribute='disks') | first %}
               <dsk string=\"{{ disk.path }}\"/>
               {% endfor %}
               </dg>'"
      tags:
        - create_disk_group
