# Used to provision a rac node container
# 'this_rac_node' variable must be set

    - name: Create rac_nodes custom directories
      file:
        state: directory
        path: "{{ operating_system.rac_node_directory }}"
        mode: 0777
      become: True
      tags:
        - create_rac_nodes_custom_dirs

    - name: Create dhclient service files for rac node container
      template:
        src: ../../common/templates/dhclient.j2
        dest: "{{ operating_system.rac_node_directory }}/dhclient-{{ item.0.name }}-{{ item.1.internal_network_name }}.service"
        owner: root
        group: root
        mode: 0644
      become: True
      with_subelements:
        - "{{ docker.containers | selectattr('name', 'equalto', this_rac_node) | list }}"
        - networks
      tags:
        - add_dhclient_services

    - name: Create network management scripts for rac node container
      template:
        src: ../../common/templates/rac-node-networks.j2
        dest: "{{ operating_system.scripts_directory }}/networks-{{ item.name }}.sh"
        owner: root
        group: root
        mode: 0744
      become: True
      with_items:
        - "{{ docker.containers | selectattr('name', 'equalto', this_rac_node) | list }}"
      tags:
        - add_network_scripts

    - name: Create rac node container
      docker_container:
        name: "{{ item.name }}"
        hostname:  "{{ item.hostname }}"
        image: "{{ this_image }}"
        state: started
        privileged: True
        volumes:
          "{{ item.volumes }}"
        command: "{{ item.command }}"
        shm_size: "{{ item.shm_size }}"
      with_items:
        - "{{ docker.containers | selectattr('name', 'equalto', this_rac_node) | list }}"
      tags:
        - create_rac_node_container

    - name: Create asm disk udev configuration file
      template:
        src: ../../common/templates/99-asm-disks.rules.j2
        dest: "{{ operating_system.rac_node_directory }}/99-asm-disk.rules"
        owner: root
        group: root
        mode: 0644
      become: True
      tags:
        - create_asm_disk_udev_file

    - name: Enable asm disk udev configuration
      command: >
        /usr/bin/docker exec {{ this_rac_node }}
        /usr/bin/ln -s /usr/lib/custom_services/99-asm-disk.rules /etc/udev/rules.d/
      become: True
      register: command_result
      changed_when: (command_result.rc == 0 ) and ('File exists' not in command_result.stderr)
      failed_when: (command_result.rc != 0) and ('File exists' not in command_result.stderr)
      tags:
        - enable_udev

    - name: Reload udev rules
      command: "/usr/bin/docker exec {{ this_rac_node }} {{ item }}"
      become: True
      with_items:
        - /usr/sbin/udevadm control --reload-rules
        - /usr/sbin/udevadm trigger
      tags:
        - reload_udev

    - name: Add networks to rac node
      command: "{{ operating_system.scripts_directory }}/networks-{{ item.name }}.sh"
      become: True
      with_items:
        - "{{ docker.containers | selectattr('name', 'equalto', this_rac_node) | list }}"
      tags:
        - add_rac_node_networks
