



asm_disk_groups:
  - group: DATA
    disks:
      - rawpath: /dev/sdd
        udevpath: /dev/asmdisks/asm-clu-121-DATA-disk1
        type: block
      - rawpath: /dev/sde
        udevpath: /dev/asmdisks/asm-clu-121-DATA-disk2
        type: block
      - rawpath: /dev/sdh
        udevpath: /dev/asmdisks/asm-clu-121-DATA-disk3
        type: block
  - group: NDATA
    disks:
      - path: /oraclenfs/asm-clu-121-NDATA-disk1
        type: file
      - path: /oraclenfs/asm-clu-121-NDATA-disk2
        type: file
      - path: /oraclenfs/asm-clu-121-NDATA-disk3
        type: file

operating_system:
  rac_node_directory: /srv/docker/rac_nodes/custom_services
  pipework_directory: /srv/docker/scripts
  pipework_file: pipework
  grid_infrastructure:
    users:
      - name: grid
        title: owner
        uid: 54325
    groups:
      - name: oinstall
        title: inventory
        gid: 54421
      - name: asmdba
        title: osdba
        gid: 54422
      - name: asmoper
        title: osoper
        gid: 54423
      - name: asmadmin
        title: osasm
        gid: 54424

docker:
  networks:
    - type: public
      name: pub
      subnet: 10.10.10.0
      cidr: 24
    - type: private
      name: priv
      subnet: 11.11.11.0
      cidr: 24

  containers: 
    - name: bind
      hostname: bind
      type:
      image: sethmiller/bind
      ports:
        - "53:53/tcp"
        - "53:53/udp"
      volumes:
        - "/srv/docker/bind:/data"
      networks:
        - name: "pub"
          ipv4_address: "10.10.10.10"
      command: "-4"
      env:
        WEBMIN_ENABLED: "false"

    - name: dhcpd
      hostname: dhcpd
      type:
      image: networkboot/dhcpd
      config_directory: /srv/docker/dhcpd
      config_file: dhcpd.conf
      volumes:
        - "/srv/docker/dhcpd:/data"
        - "/srv/docker/bind/bind/etc:/keys"
      networks:
        - name: "pub"
          ipv4_address: "10.10.10.11"
        - name: "priv"
          ipv4_address: "11.11.11.11"
      dns: 10.10.10.10

    - name: nfs
      hostname: nfs
      type:
      image: sethmiller/nfs
      config_directory: /srv/docker/nfs
      config_file: ganesha.conf
      volumes:
        - "/srv/docker/nfs:/etc/ganesha"
        - "/oraclenfs:/oraclenfs"
      dns: 10.10.10.10

    - name: rac1
      hostname: rac1
      type: rac_node
      image: sethmiller/giready
      volumes:
        - "/srv/docker/rac_nodes/custom_services:/usr/lib/custom_services"
        - "/oracledata/stage:/stage"
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      networks:
        - name: pub
          dhcp_hostname: rac1
          dhclient_pid: /var/run/dhclient-eth1.pid
          ipv4_address: 0.0.0.0
          cidr: 24
          internal_network_name: eth1
          external_network_name: rac1-pub
        - name: priv
          dhcp_hostname: rac1-priv
          dhclient_pid: /var/run/dhclient-eth2.pid
          ipv4_address: 0.0.0.0
          cidr: 24
          internal_network_name: eth2
          external_network_name: rac1-priv
      dns: 10.10.10.10
      shm_size: 2048m
      command: "/usr/lib/systemd/systemd --system --unit=multi-user.target"
