asm_disk_groups:
  - group: DATA
    disks:
      - path: /dev/asmdisks/asm-clu-121-DATA-disk1
        type: block
      - path: /dev/asmdisks/asm-clu-121-DATA-disk2
        type: block
      - path: /dev/asmdisks/asm-clu-121-DATA-disk3
        type: block

  - group: NDATA
    disks:
      - path: /oraclenfs/asm-clu-121-NDATA-disk1
        type: file
      - path: /oraclenfs/asm-clu-121-NDATA-disk2
        type: file
      - path: /oraclenfs/asm-clu-121-NDATA-disk3
        type: file
