


asm_disk_groups:
  - group: DATA
    disks:
      - rawpath: /dev/sdd
        udevpath: /dev/asmdisks/asm-clu-121-DATA-disk1
        type: block
      - rawpath: /dev/sde
        udevpath: /dev/asmdisks/asm-clu-121-DATA-disk2
        type: block
      - rawpath: /dev/sdf
        udevpath: /dev/asmdisks/asm-clu-121-DATA-disk3
        type: block
  - group: NDATA
    disks:
      - path: /oraclenfs/asm-clu-121-NDATA-disk1
        type: file
      - path: /oraclenfs/asm-clu-121-NDATA-disk2
        type: file
      - path: /oraclenfs/asm-clu-121-NDATA-disk3
        type: file

operating_system:
  grid_infrastructure:
    users:
      - name: grid
        title: owner
        uid: 54325
    groups:
      - name: oinstall
        title: inventory
        gid: 54421
      - name: asmdba
        title: osdba
        gid: 54422
      - name: asmoper
        title: osoper
        gid: 54423
      - name: asmadmin
        title: osasm
        gid: 54424

docker:
  networks:
    - type: public
      name: pub
      subnet: 10.10.10.0
      cidr: 24
    - type: private
      name: priv
      subnet: 11.11.11.0
      cidr: 24
