
    - name: Create new rac node container
      include: ../../common/tasks/start_rac_node.yml this_image=giinstalled
      tags:
        - create_additional_container

    - block:
        - name: Add new rac node container into cluster
          command: >
                 /usr/bin/docker exec {{ first_rac_node }} su -
                 {{
                   operating_system.grid_infrastructure.users |
                   selectattr('title', 'equalto', 'owner') |
                   map(attribute='name') |
                   first
                 }} -c '/u01/app/12.1.0/grid/addnode/addnode.sh
                 "CLUSTER_NEW_NODES={% raw %}{{% endraw %}{{ this_rac_node }}{% raw %}}{% endraw %}"
                 "CLUSTER_NEW_VIRTUAL_HOSTNAMES={% raw %}{{% endraw %}{{ this_rac_node }}-vip{% raw %}}{% endraw %}"
                 -waitforcompletion -silent -ignoreSysPrereqs -force -noCopy'
          register: add_new_node_result
          changed_when: (add_new_node_result.rc == 0 ) or (add_new_node_result.rc == 6 )
          failed_when: (add_new_node_result.rc != 0) and (add_new_node_result.rc != 6 )
      always:
        - name: Print readable previous command output
          debug:
            var: add_new_node_result.stdout_lines
      tags:
        - add_new_node_to_cluster

    - block:
        - name: Modify the root script to show output
          command: "/usr/bin/docker exec {{ this_rac_node }} sed -i '/rootmacro.sh/s/$/ -stdout/' /u01/app/12.1.0/grid/root.sh"
          
        - name: Run grid infrastructure root scripts
          command: "/usr/bin/docker exec {{ this_rac_node }} /u01/app/12.1.0/grid/root.sh"
      tags:
        - configure_grid_add_node_root

    - name: Relink database binaries for RAC
      command: >
             /usr/bin/docker exec {{ this_rac_node }} su -
             {{
               operating_system.database.users |
               selectattr('title', 'equalto', 'owner') |
               map(attribute='name') |
               first
             }} -c "export ORACLE_HOME=/u01/app/oracle/product/12.1.0/dbhome_1 && make -f $ORACLE_HOME/rdbms/lib/ins_rdbms.mk rac_on && make -f $ORACLE_HOME/rdbms/lib/ins_rdbms.mk ioracle"
      tags:
        - relink_database_binaries_for_rac
