
    - name: Query the list of running rac node containers
      command: >
               /usr/bin/docker ps --filter name=rac --format={% raw %}'{{ .Names }}'{% endraw %}
      register: nodes
      tags:
        - query_rac_node_containers

    - name: Enable nfs mount
      command: >
        /usr/bin/docker exec {{ item }}
        /usr/bin/ln -s /usr/lib/custom_services/oraclenfs.mount /etc/systemd/system/
      become: True
      register: command_result
      changed_when: (command_result.rc == 0 ) and ('File exists' not in command_result.stderr)
      failed_when: (command_result.rc != 0) and ('File exists' not in command_result.stderr)
      with_items:
        - "{{ nodes.stdout_lines }}"
      tags:
        - enable_nfs_mount

    - name: Reload systemd
      command: >
        /usr/bin/docker exec {{ item }}
        /usr/bin/systemctl daemon-reload
      become: True
      with_items:
        - "{{ nodes.stdout_lines }}"
      tags:
        - reload_systemd_for_nfs

    - name: Start nfs mount
      command: >
        /usr/bin/docker exec {{ item }}
        /usr/bin/systemctl start oraclenfs.mount
      become: True
      with_items:
        - "{{ nodes.stdout_lines }}"
      tags:
        - start_nfs_mount
