
    - block:
        - name: Create database
          command: >
                 /usr/bin/docker exec {{ first_rac_node }} su -
                 {{
                   operating_system.database.users |
                   selectattr('title', 'equalto', 'owner') |
                   map(attribute='name') |
                   first
                 }} -c "/u01/app/oracle/product/12.1.0/dbhome_1/bin/dbca
                 {{
                   databases |
                   selectattr('version', 'equalto', '12.1.0.2') |
                   map(attribute='parameters') |
                   first | join(' ')
                 }}"
          register: create_database_result
          changed_when: (create_database_result.rc == 0 ) or (create_database_result.rc == 6 )
          failed_when: (create_database_result.rc != 0) and (create_database_result.rc != 6 )
      always:
        - name: Print readable previous command output
          debug:
            var: create_database_result.stdout_lines
      tags:
        - create_database
