

- hosts: all
  gather_facts: False


  tasks:
    - include_vars: main.yml

    - debug:
        msg: >-
             /usr/bin/docker exec {{ first_rac_node }} su -
             {{
               operating_system.grid_infrastructure.users |
               selectattr('title', 'equalto', 'owner') |
               map(attribute='name') |
               first
             }} -c "/stage/{{
               installation_files |
               selectattr('type', 'equalto', 'grid') |
               map(attribute='version') |
               first
             }}/grid/runInstaller
             {{
               installation_files |
               selectattr('type', 'equalto', 'grid') |
               map(attribute='installer_parameters') |
               first | join(' ')
             }}"
