

- hosts: all
  gather_facts: False


  tasks:
    - include_vars: main.yml

    - debug:
        msg: |
             {% for diskgroup in asm_disk_groups %} 
               {% for disk in diskgroup.disks %}
                 {% if disk.type == 'block' %}
                   KERNEL=="{{ disk.rawpath }}", SYMLINK+="{{ disk.udevpath }}", GROUP="{{ operating_system.grid_infrastructure.groups | selectattr('title', 'equalto', 'osasm') | map(attribute='gid'    ) | first }}"
                 {% endif %}
               {% endfor %}
             {% endfor %}
#      with_items:
#        - "{{ testvar }}"
