

- hosts: all
  gather_facts: False


  tasks:
    - include_vars: main.yml

    - docker_network:
        name: "{{ item.name }}"
        appends: True
        state: present
        ipam_options:
          subnet: "{{ item.subnet }}/{{ item.cidr }}"
      with_items:
        - "{{ docker.networks }}"
      register: network_stuff

    - name: Create container
      docker_container:
        name: bind
        hostname: bind
        image: sethmiller/bind
        state: started
        restart: True
        interactive: True
        tty: True
        published_ports:
          - 53:53/tcp
          - 53:53/udp
        volumes:
          - /srv/docker/bind:/data
        env:
          WEBMIN_ENABLED: "false"
        command: "-4"
        networks:
          - name: "{{ docker.networks | selectattr('type', 'equalto', 'public') | map(attribute='name') | first }}"
      with_sequence: count=2
